1. Create a 2D Numpy array with shape (3, 3) containing random integers 
between 1 and 20.

In [3]:
import numpy as np


array_2d = np.random.randint(1, 21, (3, 3))
print("Task 1:\n", array_2d, "\n")


Task 1:
 [[13 11 16]
 [18 18  2]
 [ 3  7  9]] 



2. Write a NumPy program to create a 5x5 array with random values and find 
the minimum and maximum values for each row.

In [3]:
array_5x5 = np.random.random((5, 5))
print(array_5x5)
min_values = np.min(array_5x5, axis=1)
max_values = np.max(array_5x5, axis=1)
print("Task 2:")
print("Minimum values for each row:", min_values)
print("Maximum values for each row:", max_values, "\n")


[[0.99981048 0.47934467 0.48122377 0.06933831 0.33130908]
 [0.60975627 0.78403429 0.58653588 0.50230024 0.56918778]
 [0.6622837  0.16873564 0.7982912  0.02703109 0.43089593]
 [0.69147292 0.3981119  0.59649183 0.08229191 0.87794083]
 [0.90156317 0.97591364 0.03623946 0.97378356 0.49699754]]
Task 2:
Minimum values for each row: [0.06933831 0.50230024 0.02703109 0.08229191 0.03623946]
Maximum values for each row: [0.99981048 0.78403429 0.7982912  0.87794083 0.97591364] 



3. Write a NumPy program to create a random vector of size 10 and sort it.

In [4]:
random_vector = np.random.random(10)
sorted_vector = np.sort(random_vector)
print("Task 3:\nRandom Vector:", random_vector)
print("Sorted Vector:", sorted_vector, "\n")

Task 3:
Random Vector: [0.21058394 0.62060016 0.12540304 0.65987421 0.23766403 0.87651453
 0.04534337 0.70733409 0.18054676 0.36200303]
Sorted Vector: [0.04534337 0.12540304 0.18054676 0.21058394 0.23766403 0.36200303
 0.62060016 0.65987421 0.70733409 0.87651453] 



4. Write a NumPy program to find the most frequent value in an array

In [6]:
array_to_find_mode = np.random.randint(1, 10, 20)
print(array_to_find_mode)
frequent_value = np.bincount(array_to_find_mode).argmax()
print("Task 4:\nMost frequent value:", frequent_value, "\n")


[9 8 4 9 4 4 5 9 2 9 7 6 1 9 4 1 8 1 7 9]
Task 4:
Most frequent value: 9 



5. Create a 2D array (3,8) then reshape it to a 3D array and display it.

In [8]:
import numpy as np

# Create a 2D array with shape (3, 8)
array_2d = np.random.randint(1, 10, size=(3, 8))

# Reshape the 2D array to a 3D array with shape (3, 2, 4)
array_3d = array_2d.reshape(3, 2, 4)

# Display the 2D and 3D arrays
print("Original 2D Array:")
print(array_2d)

print("\nReshaped 3D Array:")
print(array_3d)


Original 2D Array:
[[6 7 7 5 7 7 4 9]
 [1 8 8 5 8 7 6 3]
 [6 8 3 7 7 3 2 7]]

Reshaped 3D Array:
[[[6 7 7 5]
  [7 7 4 9]]

 [[1 8 8 5]
  [8 7 6 3]]

 [[6 8 3 7]
  [7 3 2 7]]]


6. Replace all even numbers in the 2D array with 0.

In [9]:
array_2d[array_2d % 2 == 0] = 0
print("Task 6:\nModified Array (even numbers replaced with 0):\n", array_2d, "\n")


Task 6:
Modified Array (even numbers replaced with 0):
 [[0 7 7 5 7 7 0 9]
 [1 0 0 5 0 7 0 3]
 [0 0 3 7 7 3 0 7]] 



7. Apply the square root function to each element of the 1D array

In [11]:
print(array_to_find_mode)
sqrt_array = np.sqrt(array_to_find_mode)

print("Task 7:\nSquare root of the array:", sqrt_array, "\n")


[9 8 4 9 4 4 5 9 2 9 7 6 1 9 4 1 8 1 7 9]
Task 7:
Square root of the array: [3.         2.82842712 2.         3.         2.         2.
 2.23606798 3.         1.41421356 3.         2.64575131 2.44948974
 1.         3.         2.         1.         2.82842712 1.
 2.64575131 3.        ] 



8. Write a NumPy program to create a 3x3 array with random values and 
subtract the mean of each row from each element.


In [12]:
array_3x3 = np.random.random((3, 3))
mean_subtracted_array = array_3x3 - np.mean(array_3x3, axis=1, keepdims=True)
print("Task 8:\nMean subtracted array:\n", mean_subtracted_array, "\n")


Task 8:
Mean subtracted array:
 [[ 0.01015008  0.40510403 -0.41525411]
 [ 0.003418    0.1742904  -0.1777084 ]
 [ 0.16415576 -0.03458243 -0.12957333]] 



9. Create a 1D array containing the first 20 odd numbers

In [14]:
odd_numbers = np.arange(1, 21, step=2)
print("Task 9:\nFirst 20 odd numbers:", odd_numbers, "\n")


Task 9:
First 20 odd numbers: [ 1  3  5  7  9 11 13 15 17 19] 



10. Write a NumPy program to create a 5x5 array with random values and find 
the second-largest value in each column.

In [7]:
array_5x5_task10 = np.random.random((5, 5))

In [8]:

print(array_5x5_task10)
second_largest_values = np.partition(array_5x5_task10, -2, axis=0)[-2, :]
print("Task 10:\nSecond-largest values for each column:", second_largest_values, "\n")


[[0.22713993 0.93145605 0.02145509 0.73670153 0.96318997]
 [0.5733608  0.28225248 0.61301385 0.36667105 0.73989248]
 [0.54515449 0.96923677 0.84834129 0.07522764 0.21485485]
 [0.93826006 0.12358852 0.53949125 0.66972464 0.07579362]
 [0.49319613 0.49374071 0.51449301 0.92150856 0.64656057]]
Task 10:
Second-largest values for each column: [[0.22713993 0.12358852 0.02145509 0.66972464 0.07579362]
 [0.49319613 0.49374071 0.51449301 0.07522764 0.21485485]
 [0.54515449 0.28225248 0.53949125 0.36667105 0.64656057]
 [0.5733608  0.93145605 0.61301385 0.73670153 0.73989248]
 [0.93826006 0.96923677 0.84834129 0.92150856 0.96318997]] 



11. Write a NumPy program to create a 4x4 array with random values and find 
the sum of each row.


In [10]:
array_4x4_task11 = np.random.random((4, 4))
sum_of_each_row = np.sum(array_4x4_task11, axis=1)
print("Task 11:\nSum of each row:", sum_of_each_row)

Task 11:
Sum of each row: [2.15992419 0.41916546 1.86036133 1.34453161]
